name: CI CD

on:
   push:
     branches:    
      - master
     tags:
       - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100' # SDK Version to use.
      - name: Build with dotnet
        run: dotnet build --configuration Release
      
      - name: Deploy to Pre Production Environment
        if: success()
        uses: AkhileshNS/heroku-deploy@v3.0.0
        with:
          # This will be used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          # Email that you use with heroku
          heroku_email: elhajjaji.anas@gmail.com
          # The appname to use for deploying/updating
          heroku_app_name: thawing-plateau-89576
          # Will deploy using Dockerfile in project root.
          usedocker: true
      
      - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build image
        if: success()
        run: docker build -t ${GITHUB_REPOSITORY}:${IMAGE_TAG} .
      
      - name: Push to docker registry
        if: success()
        uses: actions-hub/docker@master
        with:
        args: push ${GITHUB_REPOSITORY}:${IMAGE_TAG}